Lesson  2
Vladislav-gif666/js-course pull request #3
Opened 2021-07-15 19:28 UTC by Vladislav-gif666

2021-07-15 19:28 UTC, Vladislav-gif666 commented
Все сделал кроме 8 задания со *

2021-07-16 15:04 UTC, Om1X requested changes

2021-07-16 15:04 UTC, Om1X commented on main.js
> +    if(a > 0 && b > 0) {
`>= 0`

2021-07-16 15:04 UTC, Om1X commented on main.js
> +    } else if(a < 0 && b > 0 || a > 0 && b < 0) {
это условие можно опустить

2021-07-16 15:04 UTC, Om1X commented on main.js
> +        }
забыли про пункт

> использовать функции из пункта 5

также при наличии return break не имеет никакого смысла, ибо до него очередь никогда не дойдет, т.е. код недостижим.

2021-07-16 15:04 UTC, Om1X commented on main.js
> +    a = null == 0; //false Не пойму как null может быть 'не больше 0' не равен ему и в то же время 'больше либо равен 0'
такова специфика выражений с null, при нестрогом вроде как ноль при строгом сравнении он не ноль

2021-07-22 16:51 UTC, closed without merging